---
- name: create /etc/sysctl.d directory
  file: path=/etc/sysctl.d state=directory

- sysctl: name="net.core.somaxconn" value={{ highload_somaxconn }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.core.rmem_max" value={{ highload_rmem_max }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.core.wmem_max" value={{ highload_wmem_max }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.core.rmem_default" value={{ highload_rmem_default }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.core.wmem_default" value={{ highload_wmem_default }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.core.optmem_max" value={{ highload_optmem_max }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_rmem" value="{{ highload_tcp_rmem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_wmem" value="{{ highload_tcp_wmem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_mem" value="{{ highload_tcp_mem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.udp_mem" value="{{ highload_udp_mem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

- sysctl: name="net.ipv4.ip_local_port_range" value="{{ highload_ip_local_port_range }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_tw_reuse" value="{{ highload_tcp_tw_reuse }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

- sysctl: name="net.core.netdev_max_backlog" value="{{ highload_netdev_max_backlog }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_max_syn_backlog" value="{{ highload_tcp_max_syn_backlog }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_max_tw_buckets" value="{{ highload_tcp_max_tw_buckets }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_fin_timeout" value="{{ highload_tcp_fin_timeout }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

- sysctl: name="net.ipv4.tcp_slow_start_after_idle" value="{{ highload_tcp_slow_start_after_idle }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_window_scaling" value="{{ highload_tcp_window_scaling }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_timestamps" value="{{ highload_tcp_timestamps }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_sack" value="{{ highload_tcp_sack }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_keepalive_intvl" value="{{ highload_tcp_keepalive_intvl }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_keepalive_probes" value="{{ highload_tcp_keepalive_probes }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_synack_retries" value="{{ highload_tcp_synack_retries }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="net.ipv4.tcp_max_orphans" value="{{ highload_tcp_max_orphans }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

- modprobe:
    name: tcp_cubic
    state: present
- modprobe:
    name: ip_conntrack
    state: present    

- sysctl: name="net.ipv4.tcp_congestion_control" value="{{ highload_tcp_congestion_control }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="fs.file-max" value="{{ highload_fs_file_max }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

- sysctl: name="net.ipv4.udp_rmem_min" value="{{ highload_udp_rmem_min }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
  when: highload_tune_udp

- sysctl: name="net.ipv4.udp_wmem_min" value="{{ highload_udp_wmem_min }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
  when: highload_tune_udp

- pam_limits:
    domain: '{{ item }}'
    limit_type: '-'
    limit_item: nofile
    value: '{{ highload_limits_nofile }}'
  with_items:
    - '*'
    - 'root'
    - 'nginx'

- sysctl: name="net.nf_conntrack_max" value="{{ highload_nf_conntrack_max }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
- sysctl: name="vm.max_map_count" value="{{ highload_vm_max_map_count }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
