---
#socket listen backlog
highload_somaxconn: '3240000'

# adjust memory to 1.677MB – endless memory :-)
highload_rmem_max: '167772160'
highload_wmem_max: '167772160'
highload_rmem_default: '167772160'
highload_wmem_default: '167772160'
highload_optmem_max: '2048000'
highload_tcp_rmem: '1024000 8738000 1677721600'
highload_tcp_wmem: '1024000 8738000 1677721600'
highload_tcp_mem: '1024000 8738000 1677721600'
highload_udp_mem: '1024000 8738000 1677721600'

highload_ip_local_port_range: "1025 65000"

highload_tcp_window_scaling: '1'

#This allows reusing sockets in TIME_WAIT state for new connections when it is safe from protocol viewpoint. 
#Default value is 0 (disabled). It is generally a safer alternative to tcp_tw_recycle
highload_tcp_tw_reuse: '1'

#This enables fast recycling of TIME_WAIT sockets. The default value is 0 (disabled). Should be used with caution with loadbalancers.
highload_tcp_tw_recycle: '0'
highload_tcp_timestamps: '1'
highload_tcp_sack: '1'

#This determines the wait time between isAlive interval probes.
highload_tcp_keepalive_intvl: 30

#This determines the number of probes before timing out
highload_tcp_keepalive_probes: 5


highload_netdev_max_backlog: '50000'

#Backlog Packets Before Drop
highload_tcp_max_syn_backlog: '3240000'
highload_tcp_max_tw_buckets: '1440000'
highload_tcp_fin_timeout: '15'

# Disable TCP slow start on idle connections
highload_tcp_slow_start_after_idle: '0'

highload_tcp_congestion_control: 'cubic'

# Number of SYN+ACK packets sent before the kernel gives up on the connection.
highload_tcp_synack_retries: '1'

# Maximum number of TCP sockets not attached to any user file handle, held by system.
highload_tcp_max_orphans: '400000'

# If your servers talk UDP, also up these limits
highload_udp_rmem_min: '8192'
highload_udp_wmem_min: '8192'
highload_tune_udp: false


#File Descriptors
highload_limits_nofile: 500000
highload_fs_file_max: 10000000

#Netfilter tuning
highload_nf_conntrack_max: 1000000

highload_vm_max_map_count: 262144
